language: scala

before_script: cd play-rest-api

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2

jdk:
- oraclejdk8

scala:
  - 2.12.2

services:
  - docker

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - sbt docker:publish

notifications:
  pushover:
    api_key:
      secure: dr+GDy5vBNsDFnuU93pGliyDgwvqNC/F5A2Aj89iYiHLImL8VgQEvW/PRts7UittPygpzyJJckaO7hBUfML2+kHIP3umOaXXmxbMVcSOPXIte730EG237Kb1uaeHv5D33FfaY5ZkPwLvTm1nbtSm3ulVBM9agIxWxpYzKbshFLXY5LBvsoYHfMDW8Dsn+qPB0iqaMFxms6pREFQwKHeqBwSyc2GCW8J1zXyLrLyIsyNboocYNquiZpUNNgzObUZGMTPXYSwslq6IG5GIGkW2hnn+/cdS5tIWRiDJZLXQPxHK3GTrG/J984Ewh44Sd3/guiSG55BF04YZ8gjVOskd7z+eCnXQUkAS/w+yn7kMRbub7DNA0/7546+/GZG8q0OB2wfXO8+N6aJ6AMh5EGIjs4Hv0WEjx1pvEZFCAI7BhY059aPFSYhqOeBdSJW3FwrLmvEVrn4yf1FT6AjJVNSYd41ounwwdngboaMLyaRIjZw6NxA9VBHFFBu0PiRePGTwrklHY14uNE4TBgOS9/OlCFlnmoZk3lEj36frfwtjJeAks/xdVCFN/H/QzGVhEnTwj64/ms42yzPUo9xF3dyPEuBlKUuxBACAdI4yK/H3eqBuWB1PCBEgs1jBh/oEWL6J7aSHaTk4PQSBeGB7udAmcoC4YqlNiMhR+LcGIa1UGZ4=
    users:
      secure: 0HOm9aUrkGF2FCB9k6fV11j34Vfxot+u534N66vdMiIHsKfUn+Lc/oOI2dA/l1aLGBN97uRtmklrHv6KlDJylPzSSa6mlFT3SBC71TnkNGRy6XrH3qx/Xs/MC+K0b/DI2jTh71q2+gX5tK1eEiRmDqA88rGVs8zjAaVEauOVOvdB81ynWfsA8ihDvXOn8TGPZebaVfuHk5IZCUFK9WFQG9mZ8m8bGxlaXL2/7OYpLdz1gCCjz9Ha5xRdopjb9ngZAEjjxOGkcnwdEBrM7pwyN6grPc0orcPj6L2q3Lfq7x4TeO0JauyrImNdINedbApg4yozCQ7iv81je4/BpRb9DlW0ZLxa5ERivKYScJNjpLt6JUEb9LzTms8TNYhtmzBqPdIFeOarSt/KpL32d1veNy9/wfkkP7Q4jjv+kn4LdUatTHozlLteGM1Ju82Kn01QuTtr+hdaIhzLSpQIOcGwzRgfj3JioASKi7XU+HUkC4zu/BbXkLP2G4nXl1/1AT54/8ViQ8Q/tqZ5ydBfHtQUs4FkVCe0cmVYKj8NJDNYcbWwC5w6wduN8vbt0w0YLIwD4RCVfJObIXlyRsbnMbKdU+fv7kIodjJxeZBnSEcs5QuQDOZ7w+AhYEu0fx7EDyIaUMXEmrj7ocwGTLeJDeFajjNi8GEE7PPd/8U1V3CcTbs=

env:
  global:
    - secure: QSgVStd3GUVTOstqDL5940T/f/4QwFrGqDEyrDhRFIyoaWChvClMuN7yJcKF3gyWZRbsIu2ZzdLhYbjtOM5xeUiaKg4R86mbE4Sdu+Ise/XT6ywRNM45ck793VblPJaTKdrBNmqdtFlNctPbY79DTpabGBYgpVVNmzpJecyr//SOVzlb4GVYR56uRKKgv8gQ1Yj9Y1D2mtvl9pnxG5+MFETAnOL36UxqLHVmTPwx6LHz7/iPmY2GCnavmxxEsy1PtWvpjQz62XQ+SEzKRzE8l63QWfWXioS4Fa6A9VA2SRgQ0yQ6EBD/V+bjMxUOI3CNl5R8rdvYtVENEuPqdz7l7aDqzK0qKaNFKMPlU2W5DVZNzXyKB1w7dX0aeyOh7sD5iRqKdQU4m5OOgXmMiWgu3htq9NErhkqm+ZKUg7sbRbCC9n4Z5YwatvoBskSP1M/57A9ECmbzrKXJoTGfVLwLKxBtO/f1bO+O5ikTKuKwk3wjuqgLAsqEE00+KVCmh7wxuNFE646H9HoWFL6O0cCiX2kB6tPinKH40imG1XZYTkmH5Kz4GG1zB2Dp7x8oqyii87GmvtxX6N+TXssSVoR1hAWrP5y540YzYqgCcIqoH/iSCJg+FEqH7/x483WdhJG25saLAk1298VNS1FyzT8dTy+A0/pYJne/ScrxmSonNug=
    - secure: J5finiTIoMH2eRwul+347i76uPvuoFjp3BHrQWuj7FDsyOIKz+O53bC+eWhoK3JTwW0ckPUFwF0dE9BqOV/xVWkn7t0FXxUBG30TpAuO3J/DRGRUzgkIfEtSJesP6c8yLYm+mPX3CknWO3FB5h1ynYmCN+B3rDMj4L9gdIgEo9Eedk3g9kvZ97LzXqa3aoP8t6NN5vlTej7RbBB8FZ2P4YG4055Nr+qoe9HHd9Hge5rbBAOxZjC4rnsJci18s5EWfegj15x1Q8eonnNE7vx7KxLdJ6RipIuo+kZ5qaggYfx3SfUBH/457GIZgXDWYclD9+2nbIsZBb0wQ1sLqg9W/EfMLcDhC0hxMoIxl5LkGg4rncQhi1rL4eFuuUYJj83QtpuoP187eVyHacbi6vRncRQTYiXTHFyPfoxQFQo0xUa8/j6ecp0Hf2QJ1xa0gYerHXTIohAXpYkWoJH4qe+rx9dlmJ+rpsTDQ9lp3nYhl63yqlUXMZL+NXROvJJnnjQXG9xf0I5UVGqxDbTY2A/zoEWr8wUHvfWVpUxw9yHxKtt4cgKBK+UOMrxsXPzZmFr0CnxdffhUDTX3AGzPZQLb+Y56M3wBAFk2r6AwyDNNKz8QgLDRb6NfQ1uYmGedR1gzZM6QaKEUSkPE8tL9RouHXC4Fnm8MSv4I0nsaaFWIvjA=
    - secure: U6X6I+MCJ3ciZMDvDX93Jscsjc4pckyHGX129oGAbO7UY+iqtA2nyVoEZRHgtligkzGsQwbGRdhtThouwDslgvVSekybHLAuGg+/TrGOyRrOKkg8B+3+QY+C4YadfaEDklBbGp2mS9iWMlIB0e8PlLetTzAL+xuiRC3vWoPpxyRcqfpyeGbqa7FmtacGsfgFvpzk0ooU2dRA/xRr1OT3/KHQ1p94Z/TWaef16diX2Wz4yGe+a7m1fBmW9GLPBxO5OLgwXULdM2CRTazICiYrNJ0/KD+a9GDaF+zHh8n3Ao85b4VT7sf9fSW8dS4GkY4t6PKEFqmBG/c/+eGEHQAd9tR6JOG3xK9teYFJHSQlxLaxUh3xCCWh4E21Y00dKx3IPNJtcq1eK9955Tr0QQq5i7jwzQAbTQ3Sw/46uHgyyd6egV+yYddVqJf3UEnYxWiPvf7TtvRTeolpEb86V0+yWBURMEOmD3uiWReRQWrhPP4NZtcfJSMNh9HYg/tzOV/oNLWSmnL9oNuZFUvTggYGM0v8RsjLhD+PF7Q8Y781C8qhumK4+7lg3pYafx4KdqGjKabIv3XMKbLo+VetWIt19nwxbJPkNU21MUTJdh0zIi0P+Ukfmdp05xKOvptl3J9u8v2XxIkE5fNbco3QNQ7tibmu3Hq9B6JawPT/SNMrM7U=
